beans:
    path: .beans
    prefix: beans-
    id_length: 4
    default_status: todo
    default_type: task

launchers:
  - name: opencode
    exec: opencode -p "Work on task $BEANS_ID"
    description: "Open task in OpenCode"
  - name: claude
    exec: claude "Work on task $BEANS_ID"
    description: "Open task in Claude Code"
  - name: crush
    exec: crush run "Work on task $BEANS_ID"
    description: "Open task in Crush"
  - name: worktree-kitty
    multiple: true
    description: "Create git worktree and open in new kitty window"
    exec: |
      #!/usr/bin/env bash
      set -euo pipefail
      
      WORKTREE_DIR=".worktrees/$BEANS_ID"
      
      # Create worktree if it doesn't exist
      if [ ! -d "$WORKTREE_DIR" ]; then
        # Clean up any stale worktree registrations
        git worktree prune
        
        # Check if branch already exists
        if git show-ref --verify --quiet "refs/heads/task/$BEANS_ID"; then
          # Branch exists, check it out in the worktree
          git worktree add "$WORKTREE_DIR" "task/$BEANS_ID"
        else
          # Create new branch
          git worktree add "$WORKTREE_DIR" -b "task/$BEANS_ID"
        fi
      fi
      
      # Open in new kitty window
      kitty @ launch --type=window --cwd="$BEANS_ROOT/$WORKTREE_DIR" \
        opencode -p "Work on task $BEANS_ID"
