// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Filter options for querying beans
type BeanFilter struct {
	// Include only beans with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude beans with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only beans with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude beans with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only beans with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude beans with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only beans with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude beans with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Include only beans that have outgoing links of these types
	HasLinks []string `json:"hasLinks,omitempty"`
	// Include only beans that are targets of links of these types
	LinkedAs []string `json:"linkedAs,omitempty"`
	// Exclude beans that have outgoing links of these types
	NoLinks []string `json:"noLinks,omitempty"`
	// Exclude beans that are targets of links of these types
	NoLinkedAs []string `json:"noLinkedAs,omitempty"`
}

type Query struct {
}
