// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Filter options for querying beans
type BeanFilter struct {
	// Include only beans with these statuses (OR logic)
	Status []string `json:"status,omitempty"`
	// Exclude beans with these statuses
	ExcludeStatus []string `json:"excludeStatus,omitempty"`
	// Include only beans with these types (OR logic)
	Type []string `json:"type,omitempty"`
	// Exclude beans with these types
	ExcludeType []string `json:"excludeType,omitempty"`
	// Include only beans with these priorities (OR logic)
	Priority []string `json:"priority,omitempty"`
	// Exclude beans with these priorities
	ExcludePriority []string `json:"excludePriority,omitempty"`
	// Include only beans with any of these tags (OR logic)
	Tags []string `json:"tags,omitempty"`
	// Exclude beans with any of these tags
	ExcludeTags []string `json:"excludeTags,omitempty"`
	// Include only beans that have outgoing links matching these filters (OR logic)
	HasLinks []*LinkFilter `json:"hasLinks,omitempty"`
	// Include only beans that are targets of links matching these filters (OR logic)
	LinkedAs []*LinkFilter `json:"linkedAs,omitempty"`
	// Exclude beans that have outgoing links matching these filters
	NoLinks []*LinkFilter `json:"noLinks,omitempty"`
	// Exclude beans that are targets of links matching these filters
	NoLinkedAs []*LinkFilter `json:"noLinkedAs,omitempty"`
}

// A link filter specifies both the link type and optionally a target bean ID.
type LinkFilter struct {
	// Link type (blocks, duplicates, parent, related)
	Type string `json:"type"`
	// Optional target bean ID - if omitted, matches any target
	Target *string `json:"target,omitempty"`
}

type Query struct {
}
